### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by xitude** [nikolajlovenhardt/laravel-google-ads#1]
Could not find package nikolajlovenhardt/laravel-google-ads at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by nikolajlovenhardt** [comment]
That is because the package hasn't been released in a stable release yet.
You'll have to add "minimum-stability": "dev" to your composer.json.

Take a look at https://getcomposer.org/doc/04-schema.md#minimum-stability
