### ISSUE TITLE
googleads/googleads-php-lib 10

### ISSUE THREAD

**Issue by coenswaans** [nikolajlovenhardt/laravel-google-ads#10]
Whats the best way to get googleads/googleads-php-lib updated?

**Comment by nikolajlovenhardt** [comment]
@coenswaans I'll update this package in 2 days. But I'm primarily waiting for the stable namespaced version of googleads php library.

**Comment by nikolajlovenhardt** [comment]
@coenswaans 

Here's the release for googleads-php-lib version 9.1.0 https://github.com/nikolajlovenhardt/laravel-google-ads/releases/tag/0.0.3-beta

**Comment by coenswaans** [comment]
Nice, will check! Thx

**Comment by markvaneijk** [comment]
Do you have any idea when you will use the latest version (10.x) of the Google Ads library?

**Comment by nikolajlovenhardt** [comment]
@markvaneijk I'll update it to version 10.x this week.

**Comment by nikolajlovenhardt** [comment]
@markvaneijk here you go. https://github.com/nikolajlovenhardt/laravel-google-ads/releases/tag/0.0.4-beta

googleads/googleads-php-lib version 11.0.0

**Comment by markvaneijk** [comment]
Thanks!
