### ISSUE TITLE
Any plans to upgrade to Laravel 5.3 ?

### ISSUE THREAD

**Issue by manshu** [nikolajlovenhardt/laravel-google-ads#11]
I am receiving error while using this package. 

[InvalidArgumentException]                                                                                                                                            
  Could not find package nikolajlovenhardt/laravel-google-ads at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by nikolajlovenhardt** [comment]
You need to set minimum-stability to dev in your composer.json in order to use this package.
I haven't released a stable version of this package yet.

Add this to your *composer.json*
```json
{
  "minimum-stability": "dev",
}
```
