### ISSUE TITLE
Composer Install Issue with googleads-php-lib 13.0

### ISSUE THREAD

**Issue by jwhulette** [nikolajlovenhardt/laravel-google-ads#12]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nikolajlovenhardt/laravel-google-ads dev-master -> satisfiable by nikolajlovenhardt/laravel-google-ads[dev-master].
    - nikolajlovenhardt/laravel-google-ads dev-master requires googleads/googleads-php-lib ~11.0.0 -> satisfiable by googleads/googleads-php-lib[11.0.0] but these conflict with your requirements or minimum-stability.

**Comment by nikolajlovenhardt** [comment]
This package hasn't been released in a stable version yet, so you'll need to add `"minimum-stability": "dev"` to your composer.json in order to use this.

**Comment by jwhulette** [comment]
Same Issue.
    "minimum-stability": "dev",
    "prefer-stable": true,


        "googleads/googleads-php-lib": "^13.0",
        "nikolajlovenhardt/laravel-google-ads":"dev-master"

**Comment by nikolajlovenhardt** [comment]
@jwhulette You require googleads-php-lib version ^13.0 and this package requires "~11.0.0"

**Comment by rathod4rathod** [comment]
I have the same issue 
Laravel 5.4 support because working on local proper but not  on the server.
