### ISSUE TITLE
two different errors

### ISSUE THREAD

**Issue by fonko** [nikolajlovenhardt/laravel-google-ads#13]
Hi sr, thanks for your library.

im getting two different erros, first error was 
![error2](https://cloud.githubusercontent.com/assets/2717577/19493579/ac89cf44-9551-11e6-8c74-28f8b89538dc.PNG)

and then i thought maybe i needed to add the Lumen part of your readme, then after following those steps i got:

![error3](https://cloud.githubusercontent.com/assets/2717577/19493608/d19e8bda-9551-11e6-8a44-dd9d1026e1f1.PNG)

i must be doing something wrong, im new to laravel and this api so im a little confuse.

i have set your code as a function inside a controller, like this:

http://pastebin.com/HDXkkZs7

but maybe im doing it wrong, i saw you have a class Service with this code but i actually don't understand what to do with that class, this is why i set a controller and then call it from a route (domain.com/controllerfunction) with your code.

**Comment by nikolajlovenhardt** [comment]
Hello @fonko,

The SoapFault exception is not related to this libarary. You'll need to ask in in the official google-ads-php library instead (https://github.com/googleads/googleads-php-lib).

Regarding your second question I'm not quite sure on how you've implemented this. If you're using Laravel, then it doesn't make sense, that you're including the Lumen service provider?

**Comment by fonko** [comment]
thanks for your answer nikolaj, actually im brand new to laravel so im not sure about lumen. If i should include, or not, the Lumen part described in your steps. But without this lumen part i was getting a nice looking json 
![campania de prueba](https://cloud.githubusercontent.com/assets/2717577/19494616/58412c0c-9556-11e6-851d-80c1f7909776.PNG)

and the issue was regarding the mutate() function.

anyhow, i will try to find out whats going on with this googleads-php-lib

if you have any suggestinos i will be very thankful ! :)

**Comment by nikolajlovenhardt** [comment]
@fonko You'll have to ask in the Google ads repository.
