### ISSUE TITLE
config_path() not found

### ISSUE THREAD

**Issue by Hoya** [nikolajlovenhardt/laravel-google-ads#15]
I'm on Lumen 5.2 trying to get your 0.0.6 beta working. It looks like you're trying to use a helper function that's not available. The error is as below:

`PHP Fatal error:  Call to undefined function LaravelGoogleAds\config_path() in /Users/ibreakshit/PhpstormProjects/sgworker/vendor/nikolajlovenhardt/laravel-google-ads/src/LaravelGoogleAds/LaravelGoogleAdsProvider.php on line 15`

I'm sure I can find a way to work around this for now but you might want to fix this.

**Comment by Hoya** [comment]
FYI https://gist.github.com/mabasic/21d13eab12462e596120

**Comment by nikolajlovenhardt** [comment]
https://github.com/nikolajlovenhardt/laravel-google-ads/releases/tag/0.0.7-beta

Thank you
