### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by bakhtari** [nikolajlovenhardt/laravel-google-ads#16]
Hi 
googleads-php-lib pack update to v24 but your package is old and v14
please update your code!
Ali

**Comment by nikolajlovenhardt** [comment]
@bakhtari Moving from v14 to v24 is a huge update due to the implementation of namespaces etc. I'll update it in the nearest future. You are welcome to open a PR.

Closing - duplicate of https://github.com/nikolajlovenhardt/laravel-google-ads/issues/8
