### ISSUE TITLE
[OAuth2Exception]   client_id required.

### ISSUE THREAD

**Issue by markhilton** [nikolajlovenhardt/laravel-google-ads#17]
when running:  php artisan googleads:token:generate

**Comment by nikolajlovenhardt** [comment]
Run `$ php artisan vendor:publish` to publish the configuration file config/google-ads.php and insert:
- developerToken
- clientId & clientSecret
- refreshToken

Please read the documentation: https://github.com/nikolajlovenhardt/laravel-google-ads ((README)[https://github.com/nikolajlovenhardt/laravel-google-ads/blob/master/README.md])
