### ISSUE TITLE
AdExchangeSeller Service

### ISSUE THREAD

**Issue by pedrodevoto** [nikolajlovenhardt/laravel-google-ads#19]
To be able to use **AdExchangeSeller** API, do I have to add the `adExchangeSeller` index to `config/google-ads.php` with all the configurations? Do I just copy the 'adWords' object?

Do I also have to add some files to `src/LaravelGoogleAds`?

**Comment by nikolajlovenhardt** [comment]
Hi @pedrodevoto,

Try updating to the new version 0.1.0
