### ISSUE TITLE
Do you have plan for Google Dfp,?

### ISSUE THREAD

**Issue by ALTELMA** [nikolajlovenhardt/laravel-google-ads#3]
I will looking for someone who working with Google-ads-libraries integrated with laravel. Yeah!! I found you guy, But unfortunately your repository have working AdWords Only.

I want to know. Do you have plan for it? or not Can I do that?

**Comment by nikolajlovenhardt** [comment]
Hello @ALTELMA,
There is no plan of integegration dfp at the moment, but you're welcome to open a PR.
