### ISSUE TITLE
wont install into  "laravel/framework": "5.4.*",

### ISSUE THREAD

**Issue by phillipmadsen** [nikolajlovenhardt/laravel-google-ads#30]
any updates coming?

**Comment by nikolajlovenhardt** [comment]
@phillipmadsen You are welcome to open a PR

**Comment by laravelcoder** [comment]
What do you mean by PR sorry not familiar with it.

**Comment by nikolajlovenhardt** [comment]
@laravelcoder PR stands for pull request

**Comment by laravelcoder** [comment]
ok so your answer to it not working on 5.4 is to do a pull request?

Are you going to update the package so it works for laravel 5.4 with the newer library is what im asking not if i can do it and push it back to you. I would love to add your package to our build but it will not work until you update it.

**Comment by laravelcoder** [comment]
ok so your answer to it not working on 5.4 is to do a pull request?

Are you going to update the package so it works for laravel 5.4 with the newer library is what im asking not if i can do it and push it back to you. I would love to add your package to our build but it will not work until you update it.

**Comment by nikolajlovenhardt** [comment]
@laravelcoder I do not plan to update the package at the moment, but as I said you are welcome to open a PR.

**Comment by nikolajlovenhardt** [comment]
I just released a fix for 5.4 and 5.5. Please see https://github.com/nikolajlovenhardt/laravel-google-ads/releases/tag/1.2.4
