### ISSUE TITLE
SoapFault - Could not connect to host

### ISSUE THREAD

**Issue by anonymuos1** [nikolajlovenhardt/laravel-google-ads#42]
Hi!

When is try the sample code (on localhost), I get this error: SoapFault - Could not connect to host.
(I have .pem file in curl.cainfo, in php.ini)

What is the problem? Thanks!

**Comment by nikolajlovenhardt** [comment]
Hi @anonymuos1,
It's difficult for me to help you debugging soapfaults in your local development environment. Also it doesn't relate directly to this package - I recommend that you open a thread on stackoverflow instead. To make it easier for others to help you should also include more details such as phpinfo etc.
