### ISSUE TITLE
when i run the composer require nikolajlovenhardt/laravel-google-ads command it failed i need solutions

### ISSUE THREAD

**Issue by RTPriyankaKumbar** [nikolajlovenhardt/laravel-google-ads#44]
Problem 1
    - nikolajlovenhardt/laravel-google-ads 1.2.7 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - nikolajlovenhardt/laravel-google-ads 1.2.6 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - nikolajlovenhardt/laravel-google-ads 1.2.5 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - nikolajlovenhardt/laravel-google-ads 1.2.4 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - nikolajlovenhardt/laravel-google-ads 1.2.3 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - nikolajlovenhardt/laravel-google-ads 1.2.2 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - nikolajlovenhardt/laravel-google-ads 1.2.1 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - nikolajlovenhardt/laravel-google-ads 1.2.0 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - Installation request for nikolajlovenhardt/laravel-google-ads ^1.2 -> satisfiable by nikolajlovenhardt/laravel-google-ads[1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by nikolajlovenhardt** [comment]
Hi @RTPriyankaKumbar,
The problem is specified in the response from composer. You have to look into "the requested PHP extension soap is missing from your system.".

**Comment by RTPriyankaKumbar** [comment]
ok sir. Thank you
