### ISSUE TITLE
AdWords API : Out of Date

### ISSUE THREAD

**Issue by rjksn** [nikolajlovenhardt/laravel-google-ads#6]
Any plan on keeping this up to date with Google's AdWords API?

The last version in yours is already deprecated and is 2 versions behind, it will be removed on 21 June 2016.

https://developers.google.com/adwords/api/docs/sunset-dates#api-versions

**Comment by nikolajlovenhardt** [comment]
You're welcome to open a PR

**Comment by nikolajlovenhardt** [comment]
Release: https://github.com/nikolajlovenhardt/laravel-google-ads/releases/tag/0.0.2-beta
